### ISSUE TITLE
Build a Frontend

### ISSUE THREAD

**Issue by caseyjohnsonwv** [caseyjohnsonwv/playlist-pigeon#9]
I'm imagining a very simple Vue.js SPA. On desktop, it's two halves - one for converting playlists, one for retrieving. On mobile, they're stacked with convert on top and retrieve below.

The UI needs a few key capabilities:
- [ ] Authentication to both Apple Music and Spotify
- [ ] Ability to create a playlist in the user's library and add songs to it
- [ ] GET & POST request functionality to `/v1/convert` on API Gateway
- [ ] Pop-up with conversion's Job ID for sharing with friends - can this be a shareable link?

[This library](https://github.com/JMPerez/spotify-web-api-js) looks promising for Spotify - not sure what's out there for Apple Music yet.

**Comment by caseyjohnsonwv** [comment]
Progress so far:
- Kinda functional UI
- 1/4 of the logic (read playlist from Spotify and send POST to `/convert` on AWS)

To do:
- Other 3/4s of the logic
- Little quality of life improvements
- Make the UI not suck
- Lots of tech debt cleanup
- Build automation
